### ISSUE TITLE
Pyflask importation issue.

### ISSUE THREAD

**Issue by bvenv** [ucl-cosmoparticles/flask#13]
Hi. I am trying to get pyFlask working, and have run into the error:
`/home/brandon/anaconda3/lib/python3.9/site-packages/pyFlask.cpython-39-x86_64-linux-gnu.so: undefined symbol: real_plan_forward_fftpack`

Do you know how I may solve this?

Sincerely

Brandon.

**Comment by arthurmloureiro** [comment]
Hi @bvenv , support for Flask and mainly the "pyFlask" implementation was dropped.

We recommend you check `glass`, the [Generator for Large Scale Structure](https://github.com/glass-dev/glass).

`glass` is fully implemented in python and integrated with CAMB and CCL. The code is in its final stages of development, and the paper presenting it is on its way. You can find the documentation for `glass` here: https://glass.readthedocs.io/en/latest/

Unfortunately, FLASK had too many issues (including interfacing it with python) and did not scale up well for Stage-IV surveys. Hence the team currently supporting it decided to drop it for something completely new :)
