### ISSUE TITLE
Directories intended to be ignored are instead created

### ISSUE THREAD

**Issue by ahallcosmo** [ucl-cosmoparticles/flask#6]
Hi,

The config_mkdir command in ini_config.cpp currently makes a new directory whenever any directory name appearing in the configuration file does not exist. This includes directories that follow a '0' in the config file, which used to be a handy way of forcing Flask to ignore strings on that line (and is still the way things are set up in the example.config). It would be good to make this function consistent with the way Flask reads the config file, so that string entries beginning with zero are ignored, for example.

Cheers,
Alex

**Comment by ntessore** [comment]
Hi Alex, thanks for reporting this bug. I have changed the ini file reading on the `develop` branch, and the changes should worm their way into the release at some point. If you test the `develop` version and find it doesn't fix your issue, please let me know.

**Comment by ntessore** [comment]
@ahallcosmo This should no longer be an issue on the master branch version. Let me know if there is still an issue.
