### ISSUE TITLE
Lognormal field shift doubt

### ISSUE THREAD

**Issue by dpiras** [ucl-cosmoparticles/flask#9]
Hey there! First of all, thank you for the continued work on such a useful tool.

I have a problem when generating lognormal fields using `FLASK`. I'm trying to produce a simple density field from a given power spectrum (Planck 2018 C_\ell); I set the info file as follows:
```
# Field number, z bin number, mean, shift, field type, zmin, zmax
# Types: 1-galaxies 2-shear

 1      1   0.0000   0.0001   1   0.95  1.05
```
and most of the config file is standard, as far as I can tell (I can share it if you think it's useful). When producing the field, I get something like this:

![image](https://user-images.githubusercontent.com/25639122/129944791-6f5fb89a-2a27-48aa-b33e-0e558568c694.png)

which looks fine to me.

Then, I want to do the same thing but with a shift of 1 (as standard for overdensity fields), so I set the info file like this:
```
# Field number, z bin number, mean, shift, field type, zmin, zmax
# Types: 1-galaxies 2-shear

 1      1   0.0000   1.0000   1   0.95  1.05
```

but then obtain a field which looks more Gaussian than lognormal:
![image](https://user-images.githubusercontent.com/25639122/129943425-0a39bcdf-76b2-4e87-9db1-cc26dd84cee1.png)

I am clearly missing something. How can I produce a lognormal density field with a minimum value of **-**1, looking more "peaky" like in the first figure?

Happy to provide any additional information. Thank you!

EDIT: the minimum value I'm looking for is -1, not 1.

**Comment by ntessore** [comment]
There seem to be two issues here. If you look at [the transformations for lognormal random variables](https://ntessore.page/txt/stat/lognormal_random_variables.html), you will find for a lognormal r.v. `Y` with shift `λ` is related to the Gaussian random variable `X` as
```
                             Y = exp(X) - λ                          (1)

```
So firstly, the shift is negative, in order to obtain lognormal fields that can have zero mean (the `exp(X)` has positive support). Secondly, the "shift" parameter `λ` is really a shape parameter, not a location parameter (since you are giving the mean of the field separately). You have relations between the normal and lognormal fields similar to

```
                     α = E[Y] + λ = exp(μ + σ²/2) .                  (4)

                      Var[Y] = α² [exp(σ²) - 1] ,                    (5)

```

You are keeping the expectation `E[Y]` of the lognormal field fixed, as well as its variance `Var[Y]` given by the angular power spectrum, and only change the shift parameter `λ`. You are hence not translating the random variable around, but changing its entire shape.

**Comment by dpiras** [comment]
Thank you for your answer and your notes, Nicolas! 

I agree with you I interpret the shift parameter with a minus sign in front - i.e., when I write `shift = 1.0000`, I actually mean that it should be subtracted from the field.

I think I get your second point, but I guess I'm confused about what I'd _expect_ to obtain from `FLASK`. I believe a lognormal field should be fully described by three parameters (mean, variance, shift). How should I setup the info file in order to obtain a lognormal field with the required power spectrum, 0 mean, and with shift of 1, such that it could represent a matter overdensity field with minimum value of 1?

**Comment by ntessore** [comment]
You would need to set the shift to `-1` such that the smallest possible value of `Y = exp(X) - λ` is `1`. But such a lognormal field does not exist, which you can see from `(4)` above: the l.h.s. is negative, while the r.h.s. is always positive.

**Comment by dpiras** [comment]
Oh, sorry about that, I actually meant a minimum possible value of **-1**!

**Comment by ntessore** [comment]
In which case the distribution is the one you see. The value called "shift" is a shape parameter, and the difference between `α ≪ Var[Y]` (blue) and `α ≃ Var[Y] ` (orange) is very large. See below for your values and a typical variance of `0.4`.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/3993688/130066668-623fdc32-1a71-4a1a-bd5d-355507729f3c.png">

**Comment by ntessore** [comment]
If you don't trust this plot, think about it like this: The variance of the underlying Gaussian r.v. is given by
```

                                ⎛     Var[Y] ⎞
                       σ² = log ⎜ 1 + ―――――― ⎜ .                     (6)
                                ⎝       α²   ⎠
```
If your `α`, i.e. lognormal mean plus shift, is very small, the Gaussian variance is very large. The negative half of the Gaussian values `X` are thus being mapped by `exp(X) - λ` to very close to `-λ`, while the positive half is being mapped to very large values. Overall, the distribution with `λ` very small has this very sharp peak and long tail as in the blue curve, but overall a zero mean and the same variance as the orange curve.

**Comment by dpiras** [comment]
I understand this point, thank you. 

Let's rephrase my doubt then, based on your plot. I want to create a lognormal field with a distribution like the one in the orange line. I set the mean to 0, the shift to 1, and I have an angular power spectrum like this:

![image](https://user-images.githubusercontent.com/25639122/130070741-768df611-56a4-4389-9af5-7517dfdc111b.png)

If I run `FLASK` with this setup, I get the second plot in my original post, which has a distribution like this:
![image](https://user-images.githubusercontent.com/25639122/130070374-befcf948-3290-405c-9e97-bf1d49d11b02.png)

To me, this looks very symmetric (more Gaussian-like), and does not reach the minimum value of -1 - this does not look like what I'd expect, or like the orange line distribution. What I could possibly be missing?

Thank you for your patience!

**Comment by ntessore** [comment]
That looks exactly like I would expect:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/3993688/130077914-721ad37b-ed7d-48db-8c68-b396b21fd2da.png">
Note that your angular power spectrum is orders of magnitude smaller than a usual galaxy power spectrum: Your variance, which I have used in the above plot, is something like `8.859233487223482e-8` (roughly estimated).

**Comment by dpiras** [comment]
Small aside: I didn't get the latest plot. What are the orange and blue lines? Is the orange line a realisation of a lognormal field with a very small variance?

I'm getting convinced that the problem lies in the power spectrum I'm using. I've produced the power spectrum I showed as a CMB lensing power spectrum using CLASS, hence the "small" values you can see (no prefactors are included). In the example Cls provided, though, I can see a different scale. Could you confirm what power spectra are used in the example files [like this one in `data`](https://github.com/ucl-cosmoparticles/flask/blob/master/data/exampleCl-f1z1f1z1.dat)?

**Comment by ntessore** [comment]
The second plot is exactly the same as the first, using approximately your variance instead of the value of `0.4` in the first plot.

The example config does indeed use the angular power spectrum you linked. But keep in mind that a CMB signal probes very different structures than a late-time WL signal. That is to say, I'm not sure your mostly smooth, Gaussian overdensity field is not what you should be getting.

**Comment by dpiras** [comment]
Ok, in conclusion I was able to obtain a reasonable lognormal density field by switching the CLASS power spectrum from `lCl` to `nCl`. I think this solves my problem, as essentially what I was observing was a lognormal field with a very low variance (similar to a Gaussian field).

Thank you for your patience, Nicolas!

**Comment by ntessore** [comment]
You can also look at the stuff in the src/scripts folder. That’s unmaintained and almost surely out of date, but it might give you an idea for how to configure stuff.

Otherwise give me a shout on slack and I can share some private scripts to make input files.
